env: "local"

http_server:
  port: "8080"
  timeout: 4s
  idle_timeout: 60s

db:
  host: "localhost"
  port: "5432"
  sslmode: "disable"

auth:
  token_ttl: 12h

swagger:
  host: "localhost:8080"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0